In [2]:
import numpy as np
import math
import threading
import time

### Declaracion de variables

In [3]:
m=int(input("Orden de la matriz: "))
matriz=np.zeros([m,m]) #llenar todas los ceros que necesitemos
u=np.zeros([m,m]) #matriz upper
l=np.zeros([m,m]) #matriz lower
v = int(input("Numero de vectores: "))
vectores = []
x = np.zeros((m)) #vector sol
y = np.zeros((m))

Orden de la matriz: 5
Numero de vectores: 3


### Llenado de matrices

In [4]:
print("Introduce los elementos de la matriz")
for r in range(0,m): 
    for c in range(0,m):
        matriz[r,c]=(input("Elemento a["+str(r+1)+","+str(c+1)+"]"))

        matriz[r,c]=float(matriz[r,c])
        u[r,c]=matriz[r,c]
print("Introduce los coeficientes de tus vectores\n")
for r in range(v):
    vectores.append([])
    print("Introduce los coeficientes del vector V["+str(r+1)+"]")
    for c in range(m):
        b = float(input("Elemento b["+str(c+1)+"]"))
        vectores[r].append(b)
vector= np.asarray(vectores,dtype=float)
print("Sistema a resolver\n")
print(matriz)
print(vector)

Introduce los elementos de la matriz
Elemento a[1,1]-6
Elemento a[1,2]3
Elemento a[1,3]4
Elemento a[1,4]-2
Elemento a[1,5]-18
Elemento a[2,1]-1
Elemento a[2,2]12
Elemento a[2,3]-3
Elemento a[2,4]1
Elemento a[2,5]2
Elemento a[3,1]10
Elemento a[3,2]2
Elemento a[3,3]1
Elemento a[3,4]-2
Elemento a[3,5]-3
Elemento a[4,1]3
Elemento a[4,2]2
Elemento a[4,3]1
Elemento a[4,4]-10
Elemento a[4,5]3
Elemento a[5,1]1
Elemento a[5,2]0
Elemento a[5,3]6
Elemento a[5,4]-1
Elemento a[5,5]0.5
Introduce los coeficientes de tus vectores

Introduce los coeficientes del vector V[1]
Elemento b[1]-148.7
Elemento b[2]117.7
Elemento b[3]-113.8
Elemento b[4]-4.3
Elemento b[5]-29
Introduce los coeficientes del vector V[2]
Elemento b[1]-12
Elemento b[2]-102
Elemento b[3]62
Elemento b[4]-45
Elemento b[5]-113.5
Introduce los coeficientes del vector V[3]
Elemento b[1]-223
Elemento b[2]-63
Elemento b[3]-3
Elemento b[4]-52
Elemento b[5]60.5
Sistema a resolver

[[ -6.    3.    4.   -2.  -18. ]
 [ -1.   12.   -3.    1.    2

In [5]:
vectort = np.transpose(vector)
vectort

array([[-148.7,  -12. , -223. ],
       [ 117.7, -102. ,  -63. ],
       [-113.8,   62. ,   -3. ],
       [  -4.3,  -45. ,  -52. ],
       [ -29. , -113.5,   60.5]])

### Factorizacion LU

In [6]:
for k in range(0,m): #pivote
    for r in range (0,m): #renglones
        if (k==r):
            l[k,r]=1 #diagonal de unos
        elif (k<r):
            if (matriz[k,k]==0): #condicion extra para que no haya division sobre cero
                l[r,c]=0
            else:
                factor=(matriz[r,k]/matriz[k,k])
                l[r,k]=factor
            for c in range(0,m):
                matriz[r,c]=matriz[r,c]-(factor*matriz[k,c])
                u[r,c]=matriz[r,c]
print("Matriz resultante")
print("Matriz L")
print(l)
print("Matriz U")
print(u)

Matriz resultante
Matriz L
[[ 1.          0.          0.          0.          0.        ]
 [ 0.16666667  1.          0.          0.          0.        ]
 [-1.66666667  0.60869565  1.          0.          0.        ]
 [-0.5         0.30434783  0.41581259  1.          0.        ]
 [-0.16666667  0.04347826  0.68960469 -0.32158809  1.        ]]
Matriz U
[[ -6.           3.           4.          -2.         -18.        ]
 [  0.          11.5         -3.66666667   1.33333333   5.        ]
 [  0.           0.           9.89855072  -6.14492754 -36.04347826]
 [  0.           0.           0.          -8.85065886   7.46559297]
 [  0.           0.           0.           0.          24.53920596]]


### Implementacion de paralelismo con hilos

In [7]:
def solucion(l,u,vector):
    for columna in range(v):
        global c
        for r in range(m):
            summ =0
            for c in range(r):
                summ += y[c]*l[r,c]
            if(l[r,r]==0):
                y[r]=0
            else:
                y[r] = (vector[r,columna]-summ)/l[r,r]
        for r in range(m-1,-1,-1):
            summ =0
            for c in range(r+1,m):
                summ += x[c]*u[r,c]
            x[r]=(y[r]-summ)/u[r,r]
        print("Solucion X=")
        print(x)

In [8]:
%%time
threads = []
hilo = threading.Thread(target=solucion, args=(l,u,vectort,))
hilo.start()

Solucion X=
[-8.5  6.1 -4.   2.  11. ]
Solucion X=
[  7.98855666 -11.3575548  -19.52769492   0.19713562  -8.25050307]
Solucion X=
[ 5. -5. 10. 10. 11.]
CPU times: user 3.89 ms, sys: 0 ns, total: 3.89 ms
Wall time: 3.84 ms
