In [1]:
import numpy as np

In [2]:
A = np.array([[4,1,-2,2],[1,2,0,1],[-2,0,3,-2],[2,1,-2,-1]])
A

array([[ 4,  1, -2,  2],
       [ 1,  2,  0,  1],
       [-2,  0,  3, -2],
       [ 2,  1, -2, -1]])

In [97]:
def Hh(A,t):
    for i in range(0,t):
        j=i
        n = len(A)
        traza = np.trace(A)
        suma = 0
        
        # G y r
        if (A[i+1,j]<0):
            signo = -1
        else:
            signo = 1
        for it in range(1,n):
            suma += A[it,j]**2
        G = signo*suma**(1/2)
        r = ((1/2)*G**2+(1/2)*A[1,0]*G)**(1/2)
        
        # Vector w
        w = np.zeros((n,n))
        w[0,0]=0
        if i < 1:
            w[1,0]=(A[i+1,0]+G)/(2*r)
        else: 
            w[i,0]=0
        for it in range(2,n):
                w[it,0]=A[it,0]/(2*r)
        
        # Transformacion Hh
        I = np.identity((n))
        P = I - 2*w@np.transpose(w)
        
        # Transformacion de semejanza
        A=P@A@P
        trazai = np.trace(A)
        
        print(f'traza: {traza}\n G:{G} \n r:{r}\n w:{w}\n P{i+1}:{P}\n A{i+2}:{A}\n traza: {trazai}')

In [98]:
Hh(A,3)

traza: 8
 G:3.0 
 r:2.449489742783178
 w:[[ 0.          0.          0.          0.        ]
 [ 0.81649658  0.          0.          0.        ]
 [-0.40824829  0.          0.          0.        ]
 [ 0.40824829  0.          0.          0.        ]]
 P1:[[ 1.          0.          0.          0.        ]
 [ 0.         -0.33333333  0.66666667 -0.66666667]
 [ 0.          0.66666667  0.66666667  0.33333333]
 [ 0.         -0.66666667  0.33333333  0.66666667]]
 A2:[[ 4.00000000e+00 -3.00000000e+00  6.66133815e-16 -6.66133815e-16]
 [-3.00000000e+00  3.33333333e+00  1.00000000e+00  1.33333333e+00]
 [ 6.66133815e-16  1.00000000e+00  1.66666667e+00 -1.33333333e+00]
 [-6.66133815e-16  1.33333333e+00 -1.33333333e+00 -1.00000000e+00]]
 traza: 8.000000000000004
traza: 8.000000000000004
 G:3.7267799624996516 
 r:1.1637330023226864
 w:[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.86205604e-16  0.00000000e+00  0.00

In [94]:
A_tarea = np.array([[-2,3,1,-1],[3,4,2,5],[1,2,1,3],[-1,5,3,-4]])
A_tarea

array([[-2,  3,  1, -1],
       [ 3,  4,  2,  5],
       [ 1,  2,  1,  3],
       [-1,  5,  3, -4]])

In [101]:
Hh(A_tarea,2)

traza: -1
 G:3.3166247903554 
 r:3.2365007624799196
 w:[[ 0.          0.          0.          0.        ]
 [ 0.9758417   0.          0.          0.        ]
 [ 0.15448784  0.          0.          0.        ]
 [-0.15448784  0.          0.          0.        ]]
 P1:[[ 1.          0.          0.          0.        ]
 [ 0.         -0.90453403 -0.30151134  0.30151134]
 [ 0.         -0.30151134  0.95226702  0.04773298]
 [ 0.          0.30151134  0.04773298  0.95226702]]
 A2:[[-2.00000000e+00 -3.31662479e+00  5.55111512e-17  0.00000000e+00]
 [-3.31662479e+00  8.18181818e-01 -6.46920207e-01 -7.19237475e+00]
 [ 5.55111512e-17 -6.46920207e-01  2.41664763e-01  1.40909091e+00]
 [ 0.00000000e+00 -7.19237475e+00  1.40909091e+00 -5.98465814e-02]]
 traza: -1.000000000000001
traza: -1.000000000000001
 G:-7.267611837335686 
 r:6.20169829178144
 w:[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.47547983e-18 0.00000000e+00 0